version: "3"
services:
 mysql:
  container_name: video-streaming-mysql
  image: mysql
  environment:
    - MYSQL_ROOT_PASSWORD=root
    - MYSQL_DATABASE=root
  ports:
    - 8085:3306
  expose:
      - 8085
 authentication-service:
  container_name: video-streaming-authentication-service
  image: authentication-service
  ports :
   - 8080:8080
  expose:
    - 8080
  depends_on:
   mysql:
    condition: service_started
 file-upload-service:
    container_name: video-streaming-file-upload-service
    image: file-upload-service
    ports :
    - 8081:8081
    expose:
      - 8081
    depends_on:
     mysql:
      condition: service_started

